#!/bin/bash
# install.sh - Install claude-docker for use from anywhere
set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$HOME/.claude-in-docker"
DEFAULT_BIN_DIR="$HOME/.local/bin"

echo "================================"
echo "  Claude-in-Docker Installer"
echo "================================"
echo

# Install gum if not present (silent step)
install_gum() {
    if command -v gum &>/dev/null; then
        return 0
    fi

    echo "Installing gum for interactive prompts..."

    local os arch gum_url gum_version="0.14.0"
    os=$(uname -s | tr '[:upper:]' '[:lower:]')
    arch=$(uname -m)

    case "$arch" in
        x86_64) arch="x86_64" ;;
        aarch64|arm64) arch="arm64" ;;
        *) echo "Unsupported architecture: $arch"; return 1 ;;
    esac

    case "$os" in
        darwin) os="Darwin" ;;
        linux) os="Linux" ;;
        *) echo "Unsupported OS: $os"; return 1 ;;
    esac

    gum_url="https://github.com/charmbracelet/gum/releases/download/v${gum_version}/gum_${gum_version}_${os}_${arch}.tar.gz"

    local tmp_dir=$(mktemp -d)
    if curl -fsSL "$gum_url" | tar -xzC "$tmp_dir"; then
        mkdir -p "$HOME/.local/bin"
        mv "$tmp_dir/gum" "$HOME/.local/bin/"
        chmod +x "$HOME/.local/bin/gum"
        rm -rf "$tmp_dir"

        if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
            export PATH="$HOME/.local/bin:$PATH"
        fi

        echo "Gum installed to ~/.local/bin/gum"
    else
        rm -rf "$tmp_dir"
        echo "Failed to install gum"
        return 1
    fi
}

install_gum
echo

# Step 1: Configure credentials
echo "Step 1: Configure credentials"
echo "-----------------------------"

if [[ -f "$INSTALL_DIR/.env" ]]; then
    if ! gum confirm "Credentials already exist. Overwrite?"; then
        echo "Keeping existing credentials."
        SKIP_CREDENTIALS=true
    else
        SKIP_CREDENTIALS=false
    fi
else
    SKIP_CREDENTIALS=false
fi

if [[ "$SKIP_CREDENTIALS" == "false" ]]; then
    method=$(gum choose "Enter credentials interactively" "Edit config file in editor")

    if [[ "$method" == "Enter credentials interactively" ]]; then
        DEFAULT_GIT_NAME=$(git config --global user.name 2>/dev/null || echo "")
        DEFAULT_GIT_EMAIL=$(git config --global user.email 2>/dev/null || echo "")
        DEFAULT_GH_TOKEN=""
        if command -v gh &>/dev/null && gh auth status &>/dev/null 2>&1; then
            DEFAULT_GH_TOKEN=$(gh auth token 2>/dev/null || echo "")
        fi

        echo
        echo "Git Configuration:"
        GIT_USER_NAME=$(gum input --placeholder "Git user name" --value "$DEFAULT_GIT_NAME")
        GIT_USER_EMAIL=$(gum input --placeholder "Git user email" --value "$DEFAULT_GIT_EMAIL")

        echo
        echo "GitHub Token:"
        if [[ -n "$DEFAULT_GH_TOKEN" ]]; then
            if gum confirm "Found GitHub token from gh CLI. Use it?"; then
                GITHUB_TOKEN="$DEFAULT_GH_TOKEN"
            else
                GITHUB_TOKEN=$(gum input --password --placeholder "GitHub personal access token")
            fi
        else
            GITHUB_TOKEN=$(gum input --password --placeholder "GitHub personal access token")
        fi

        echo
        echo "Claude Credentials:"
        echo "(Paste the JSON from ~/.claude/.credentials.json or leave empty to use ~/.claude.json)"
        CLAUDE_CREDENTIALS=$(gum input --password --placeholder "Claude credentials JSON (optional)")

        CREDENTIALS_CONTENT="# Claude-in-Docker credentials
# Generated by install.sh on $(date)

GIT_USER_NAME=$GIT_USER_NAME
GIT_USER_EMAIL=$GIT_USER_EMAIL
GITHUB_TOKEN=$GITHUB_TOKEN
CLAUDE_CREDENTIALS=$CLAUDE_CREDENTIALS"

    else
        EDITOR_CHOICE=$(gum choose "${EDITOR:-vim}" "vim" "nano")
        USE_EDITOR=true
    fi
fi

echo

# Step 2: Choose symlink location
echo "Step 2: Choose install location"
echo "--------------------------------"

if [[ -d "$DEFAULT_BIN_DIR" ]] && [[ ":$PATH:" == *":$DEFAULT_BIN_DIR:"* ]]; then
    BIN_DIR="$DEFAULT_BIN_DIR"
    echo "Will install to: $BIN_DIR/claude-docker"
else
    echo "Default location $DEFAULT_BIN_DIR is not in PATH."
    BIN_DIR=$(gum input --placeholder "Symlink location" --value "$DEFAULT_BIN_DIR")
fi

echo

# Step 3: Build Docker image (slow part - no more interaction needed)
echo "Step 3: Building Docker image"
echo "-----------------------------"
echo "(This may take a few minutes...)"
echo

cd "$REPO_DIR/docker"
docker-compose -f compose.base.yml -f compose.global.yml build
echo "Done building image."
echo

# Step 4: Copy files to install directory
echo "Step 4: Installing files"
echo "------------------------"

mkdir -p "$INSTALL_DIR"

cp -r "$REPO_DIR/bin" "$INSTALL_DIR/"
cp -r "$REPO_DIR/docker" "$INSTALL_DIR/"
cp -r "$REPO_DIR/lib" "$INSTALL_DIR/"
cp -r "$REPO_DIR/config" "$INSTALL_DIR/"
cp -r "$REPO_DIR/completions" "$INSTALL_DIR/"

mkdir -p "$INSTALL_DIR/workspace"
chmod +x "$INSTALL_DIR/bin/"*

# Write credentials now (after install dir exists)
if [[ "$SKIP_CREDENTIALS" == "false" ]]; then
    if [[ -n "$CREDENTIALS_CONTENT" ]]; then
        echo "$CREDENTIALS_CONTENT" > "$INSTALL_DIR/.env"
        echo "Credentials saved."
    elif [[ "$USE_EDITOR" == "true" ]]; then
        cp "$REPO_DIR/.env.example" "$INSTALL_DIR/.env"
        echo "Opening $INSTALL_DIR/.env in $EDITOR_CHOICE..."
        echo "Save and close when done."
        sleep 1
        "$EDITOR_CHOICE" "$INSTALL_DIR/.env"
    fi
fi

echo "Files installed to $INSTALL_DIR"
echo

# Step 5: Create symlink
echo "Step 5: Creating symlink"
echo "------------------------"

mkdir -p "$BIN_DIR"
rm -f "$BIN_DIR/claude-docker"
ln -s "$INSTALL_DIR/bin/claude-docker" "$BIN_DIR/claude-docker"

echo "Symlink created: $BIN_DIR/claude-docker"

if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo
    echo "Warning: $BIN_DIR is not in your PATH."
    echo "Add this to your shell config (~/.bashrc or ~/.zshrc):"
    echo
    echo "  export PATH=\"$BIN_DIR:\$PATH\""
fi

echo

# Step 6: Install shell completions
echo "Step 6: Shell completions"
echo "-------------------------"

COMPLETIONS_INSTALLED=false

BASH_COMPLETION_DIR="${BASH_COMPLETION_USER_DIR:-$HOME/.local/share/bash-completion/completions}"
if [[ -n "$BASH_VERSION" ]] || [[ -f "$HOME/.bashrc" ]]; then
    mkdir -p "$BASH_COMPLETION_DIR"
    cp "$REPO_DIR/completions/claude-docker.bash" "$BASH_COMPLETION_DIR/claude-docker"
    echo "Bash completions installed."
    COMPLETIONS_INSTALLED=true
fi

if [[ -n "$ZSH_VERSION" ]] || [[ -f "$HOME/.zshrc" ]]; then
    ZSH_COMPLETION_DIR="$HOME/.zfunc"
    mkdir -p "$ZSH_COMPLETION_DIR"
    cp "$REPO_DIR/completions/_claude-docker" "$ZSH_COMPLETION_DIR/_claude-docker"
    echo "Zsh completions installed."

    if ! grep -q 'fpath.*\.zfunc' "$HOME/.zshrc" 2>/dev/null; then
        echo
        echo "To enable Zsh completions, add to ~/.zshrc:"
        echo '  fpath=(~/.zfunc $fpath)'
        echo '  autoload -Uz compinit && compinit'
    fi
    COMPLETIONS_INSTALLED=true
fi

if $COMPLETIONS_INSTALLED; then
    echo "Restart your shell to enable completions."
fi

echo
echo "================================"
echo "  Installation complete!"
echo "================================"
echo
echo "Usage:"
echo "  claude-docker         Run Claude in current directory (project mode)"
echo "  claude-docker -g      Run Claude in global workspace mode"
echo "  claude-docker --help  Show all options"
echo
